import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";
import {RoomEnvironment} from "three/addons/environments/RoomEnvironment.js";
const $=s=>document.querySelector(s),canvas=$("#scene"),loading=$("#loading"),progress=$("#progress"),status=$("#status"),error=$("#error"),errorMsg=$("#error-msg");
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdce6f0);scene.fog=new THREE.Fog(0xdce6f0,42,95);
const camera=new THREE.PerspectiveCamera(38,1,.04,260);camera.position.set(22,18,22);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.07;controls.screenSpacePanning=true;controls.minDistance=3;controls.maxDistance=90;controls.maxPolarAngle=Math.PI/2.01;
scene.add(new THREE.HemisphereLight(0xffffff,0x68768b,1.65));const sun=new THREE.DirectionalLight(0xffffff,2.25);sun.position.set(15,24,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;scene.add(sun);const fill=new THREE.DirectionalLight(0xc8dcff,.55);fill.position.set(-15,11,-12);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.ShadowMaterial({color:0x64748b,opacity:.11}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const world=new THREE.Group(),first=new THREE.Group(),second=new THREE.Group();world.add(first,second);scene.add(world);let current="both",selected=null,saved=null,down=null;
function prepare(root){const items=[];root.traverse(o=>{if(!o.isMesh)return;items.push(o);o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.side=THREE.DoubleSide;m.needsUpdate=true})});for(const o of items){const n=o.name||o.parent?.name||"";(n.startsWith("first__")?first:second).attach(o)}}
function bounds(){world.updateMatrixWorld(true);const b=new THREE.Box3();b.makeEmpty();if(first.visible)b.union(new THREE.Box3().setFromObject(first));if(second.visible)b.union(new THREE.Box3().setFromObject(second));return b}
function fit(top=false){const b=bounds();if(b.isEmpty())return;const size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3()),max=Math.max(size.x,size.z,size.y*1.55),fov=THREE.MathUtils.degToRad(camera.fov),dist=(max*.66)/Math.tan(fov/2)*(top?1.05:1.17);camera.position.copy(top?new THREE.Vector3(center.x,center.y+dist,center.z+.001):center.clone().add(new THREE.Vector3(1,.72,1).normalize().multiplyScalar(dist)));controls.target.copy(center);controls.update()}
function clear(){if(selected&&saved)selected.material=saved;selected=saved=null;$("#info").hidden=true}
function setFloor(mode){current=mode;first.visible=mode!=="second";second.visible=mode!=="first";document.querySelectorAll("[data-floor]").forEach(b=>b.classList.toggle("active",b.dataset.floor===mode));status.textContent=mode==="both"?"Entrambi i piani":mode==="first"?"Primo piano":"Secondo piano";ground.position.y=mode==="second"?-.12:-3.02;clear();requestAnimationFrame(()=>fit(false))}
function parseParts(name=""){const parts=name.split("__");return {floorCode:parts[0]||"",roomCode:parts[1]||"",instanceId:parts[2]||"",title:(parts[3]||"Elemento").replaceAll("_"," "),slot:(parts[4]||parts.at(-1)||"mesh").replaceAll("_"," "),raw:name}}
function floorLabel(code){return code==="first"?"Primo piano":code==="second"?"Secondo piano":code||"-"}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function pick(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(world,true).find(x=>x.object.isMesh&&x.object.visible);if(!hit){clear();return}clear();selected=hit.object;saved=selected.material;const arr=Array.isArray(saved)?saved:[saved];const hi=arr.map(m=>{const c=m.clone();if("emissive"in c){c.emissive.set(0x1f65d1);c.emissiveIntensity=.32}return c});selected.material=Array.isArray(saved)?hi:hi[0];const meta=parseParts(selected.name||"");$("#info-title").textContent=meta.title;$("#info-detail").textContent=`${meta.slot} · ${floorLabel(meta.floorCode)}`;$("#meta-floor").textContent=floorLabel(meta.floorCode);$("#meta-room").textContent=meta.roomCode||"-";$("#meta-instance").textContent=meta.instanceId||"-";$("#meta-slot").textContent=meta.slot||"-";const objectCode=`${meta.raw}`;$("#object-code").value=objectCode;$("#info").hidden=false}
canvas.addEventListener("pointerdown",e=>down={x:e.clientX,y:e.clientY});canvas.addEventListener("pointerup",e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5)pick(e);down=null});$("#close").onclick=clear;$("#copy-code").onclick=async()=>{const value=$("#object-code").value;try{await navigator.clipboard.writeText(value);const btn=$("#copy-code");const old=btn.textContent;btn.textContent="Copiato";setTimeout(()=>btn.textContent=old,1200)}catch{}};document.querySelectorAll("[data-floor]").forEach(b=>b.onclick=()=>setFloor(b.dataset.floor));$("#iso").onclick=()=>fit(false);$("#topview").onclick=()=>fit(true);$("#rotate").onclick=e=>{controls.autoRotate=!controls.autoRotate;controls.autoRotateSpeed=.55;e.currentTarget.classList.toggle("active",controls.autoRotate)};$("#reset").onclick=()=>{controls.autoRotate=false;$("#rotate").classList.remove("active");setFloor(current)};$("#full").onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}};
new GLTFLoader().load("./assets/casa_homestyler.glb?v=8",g=>{prepare(g.scene);setFloor("both");loading.classList.add("hidden")},p=>{if(p.total)progress.textContent=`${Math.round(p.loaded/p.total*100)}%`;else progress.textContent="Download modello…"},e=>{console.error(e);loading.classList.add("hidden");error.hidden=false;errorMsg.textContent="Il file assets/casa_homestyler.glb non è stato trovato o non è stato caricato completamente. Controlla di aver caricato l’intera cartella assets. Dettaglio: "+(e?.message||e)});
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.floor(w*d)||canvas.height!==Math.floor(h*d)){renderer.setPixelRatio(d);renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()}}function loop(){resize();controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();