import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { clone as skeletonClone } from "three/addons/utils/SkeletonUtils.js";

THREE.Cache.enabled=true;
const $=s=>document.querySelector(s), canvas=$("#scene"), loading=$("#loading"), progress=$("#progress"), status=$("#status"), statusBox=document.querySelector(".status"), errorBox=$("#error"), errorMsg=$("#error-msg");
const scene=new THREE.Scene(); scene.background=new THREE.Color(0xdce6f0); scene.fog=new THREE.Fog(0xdce6f0,42,92);
const camera=new THREE.PerspectiveCamera(38,1,.04,260); camera.position.set(22,18,22);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"}); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const controls=new OrbitControls(camera,canvas); controls.enableDamping=true; controls.dampingFactor=.07; controls.screenSpacePanning=true; controls.minDistance=3; controls.maxDistance=85; controls.maxPolarAngle=Math.PI/2.01;
scene.add(new THREE.HemisphereLight(0xffffff,0x6c7890,2.25)); const sun=new THREE.DirectionalLight(0xffffff,3.3); sun.position.set(16,25,12); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;scene.add(sun); const fill=new THREE.DirectionalLight(0xbcd4ff,1.05);fill.position.set(-15,11,-12);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.ShadowMaterial({color:0x63748b,opacity:.13}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const world=new THREE.Group(), first=new THREE.Group(), second=new THREE.Group(); world.add(first,second); scene.add(world);
const manager=new THREE.LoadingManager(), loader=new GLTFLoader(manager), texLoader=new THREE.TextureLoader(manager); const textureCache=new Map();
let manifest,selected,savedMaterial,current="both",down=null;
function tex(path,color=false){if(!path)return null;if(textureCache.has(path))return textureCache.get(path);const t=texLoader.load('./'+path);t.flipY=false;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(color)t.colorSpace=THREE.SRGBColorSpace;textureCache.set(path,t);return t}
function makeMat(spec={},opts={}){const files=spec.files||spec;const glass=opts.glass;let m;if(glass)m=new THREE.MeshPhysicalMaterial({color:0xc6e6f7,roughness:.1,metalness:0,transparent:true,opacity:.30,transmission:.55,thickness:.08,side:THREE.DoubleSide,depthWrite:false});else m=new THREE.MeshStandardMaterial({color:opts.color||0xd0d0d0,roughness:.72,metalness:.02,side:THREE.DoubleSide});if(files.diffuse){m.map=tex(files.diffuse,true);m.color.set(0xffffff)}if(files.normal)m.normalMap=tex(files.normal);if(files.roughness){m.roughnessMap=tex(files.roughness);m.roughness=1}if(files.reflect&&!files.roughness){m.metalnessMap=tex(files.reflect);m.metalness=.15}return m}
function baseSlot(name=''){const m=name.match(/(?:solid|glass)_\d+/i);return m?m[0].toLowerCase():name.replace(/_\d+$/,'').toLowerCase()}
function applyFurnitureMaterials(root,modelSpec){root.traverse(o=>{if(!o.isMesh)return;const slot=baseSlot(o.name);const spec=(modelSpec.materials||{})[slot]||{};o.material=makeMat(spec,{glass:/glass/i.test(slot),color:/glass/i.test(slot)?0xcce9f7:0xb8aaa0});o.castShadow=true;o.receiveShadow=true;o.userData.kind='Arredo';})}
function applyArchitectureMaterials(root){root.traverse(o=>{if(!o.isMesh)return;const matName=o.material?.name||o.name.split('__').at(-1);const spec=manifest.architectureMaterials[matName];if(spec){const c=spec.color||[245,245,245,255], color=new THREE.Color(c[0]/255,c[1]/255,c[2]/255);o.material=makeMat(spec,{color});const files=spec.files||{};for(const key of ['map','normalMap','roughnessMap'])if(o.material[key]){o.material[key].repeat.set(spec.repeat?.[0]||1,spec.repeat?.[1]||1);o.material[key].rotation=spec.rotation||0;o.material[key].center.set(.5,.5)}}o.castShadow=true;o.receiveShadow=true;o.userData.kind=o.name.split('__')[2]||'Architettura';})}
function floorForY(y){return y<-.1?first:second}
function reparentArchitecture(root){root.updateMatrixWorld(true);const meshes=[];root.traverse(o=>{if(o.isMesh)meshes.push(o)});for(const child of meshes){const box=new THREE.Box3().setFromObject(child), y=box.getCenter(new THREE.Vector3()).y;floorForY(y).attach(child)}}
async function loadGLTF(path){return await loader.loadAsync('./'+path)}
async function loadFurniture(){const byJid=new Map();for(const inst of manifest.instances){if(!byJid.has(inst.jid))byJid.set(inst.jid,[]);byJid.get(inst.jid).push(inst)}const jobs=[...byJid.entries()];let done=0;const workers=Array.from({length:Math.min(6,jobs.length)},async()=>{while(jobs.length){const [jid,items]=jobs.shift();try{const spec=manifest.models[jid], gltf=await loadGLTF(spec.path);applyFurnitureMaterials(gltf.scene,spec);for(const inst of items){const obj=skeletonClone(gltf.scene);obj.name=`${inst.roomId}__${inst.instanceid}__${inst.title}`;obj.position.fromArray(inst.pos);obj.quaternion.fromArray(inst.rot);obj.scale.set(inst.scale[0]*.01,inst.scale[1]*.01,inst.scale[2]*.01);obj.userData={...obj.userData,kind:'Arredo',title:inst.title,roomId:inst.roomId,floor:inst.floor};(inst.floor==='first'?first:second).add(obj)}}catch(e){console.warn('Modello non caricato',jid,e)}done++;progress.textContent=`Arredi e texture ${done}/${byJid.size}`}});await Promise.all(workers)}
function visibleBounds(){world.updateMatrixWorld(true);const box=new THREE.Box3();box.makeEmpty();[first,second].forEach(g=>{if(g.visible)box.union(new THREE.Box3().setFromObject(g))});return box}
function fit(top=false){const box=visibleBounds();if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),max=Math.max(size.x,size.z,size.y*1.55),fov=THREE.MathUtils.degToRad(camera.fov),dist=(max*.66)/Math.tan(fov/2)*(top?1.05:1.18);camera.position.copy(top?new THREE.Vector3(center.x,center.y+dist,center.z+.001):center.clone().add(new THREE.Vector3(1,.72,1).normalize().multiplyScalar(dist)));controls.target.copy(center);controls.update()}
function setFloor(mode){current=mode;first.visible=mode!=='second';second.visible=mode!=='first';world.position.y=mode==='second'?0:3;document.querySelectorAll('[data-floor]').forEach(b=>b.classList.toggle('active',b.dataset.floor===mode));status.textContent=mode==='both'?'Entrambi i piani':mode==='first'?'Primo piano':'Secondo piano';clearSelection();requestAnimationFrame(()=>fit(false))}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.floor(w*d)||canvas.height!==Math.floor(h*d)){renderer.setPixelRatio(d);renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()}}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function clearSelection(){if(selected&&savedMaterial)selected.material=savedMaterial;selected=null;savedMaterial=null;$('#info').hidden=true}function pick(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(world,true).find(h=>h.object.isMesh&&h.object.visible);if(!hit){clearSelection();return}clearSelection();selected=hit.object;savedMaterial=selected.material;const mats=Array.isArray(savedMaterial)?savedMaterial:[savedMaterial];const hi=mats.map(m=>{const n=m.clone();if('emissive'in n){n.emissive.set(0x2167d1);n.emissiveIntensity=.35}return n});selected.material=Array.isArray(savedMaterial)?hi:hi[0];let owner=selected;while(owner&&owner!==world&&!owner.userData?.title)owner=owner.parent;const title=owner?.userData?.title||selected.name.split('__')[1]||'Elemento';$('#info-title').textContent=title.replaceAll('_',' ');$('#info-detail').textContent=`${selected.userData.kind||owner?.userData?.kind||'Elemento'} · ${current==='first'?'Primo piano':current==='second'?'Secondo piano':'Casa completa'}`;$('#info').hidden=false}
canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5)pick(e);down=null});$('#close').onclick=clearSelection;document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>setFloor(b.dataset.floor));$('#iso').onclick=()=>fit(false);$('#topview').onclick=()=>fit(true);$('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;controls.autoRotateSpeed=.6;e.currentTarget.classList.toggle('active',controls.autoRotate)};$('#reset').onclick=()=>{controls.autoRotate=false;$('#rotate').classList.remove('active');setFloor(current)};$('#full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch(e){}};
async function init(){try{manifest=await fetch('./assets/manifest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('manifest HTTP '+r.status);return r.json()});progress.textContent='Caricamento architettura…';const a=await loadGLTF(manifest.architecture);applyArchitectureMaterials(a.scene);reparentArchitecture(a.scene);progress.textContent='Caricamento arredi…';await loadFurniture();setFloor('both');loading.classList.add('hidden');statusBox.classList.add('ready');status.textContent='Entrambi i piani';}catch(e){console.error(e);loading.classList.add('hidden');errorBox.hidden=false;errorMsg.textContent='Il pacchetto non è completo oppure alcuni file non sono stati caricati. '+e.message}}
function loop(){resize();controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();init();
