window.CASA_ROOMS = [
  {id:'first-living',modelKey:'first__LivingDiningRoom-116276',floor:'first',name:'Soggiorno e cucina',icon:'fa-couch',type:'indoor',entities:{temperature:'sensor.soggiorno_temperatura',humidity:'sensor.soggiorno_umidita',lights:'light.soggiorno',cover:'cover.soggiorno'}},
  {id:'first-master-bedroom',modelKey:'first__MasterBedroom-105249',floor:'first',name:'Camera matrimoniale',icon:'fa-bed',type:'indoor',entities:{temperature:'sensor.camera_matrimoniale_temperatura',humidity:'sensor.camera_matrimoniale_umidita',lights:'light.camera_matrimoniale',cover:'cover.camera_matrimoniale'}},
  {id:'first-bedroom',modelKey:'first__Bedroom-106328',floor:'first',name:'Camera',icon:'fa-bed',type:'indoor',entities:{temperature:'sensor.camera_temperatura',humidity:'sensor.camera_umidita',lights:'light.camera',cover:'cover.camera'}},
  {id:'first-master-bathroom',modelKey:'first__MasterBathroom-92592',floor:'first',name:'Bagno padronale',icon:'fa-bath',type:'indoor',entities:{temperature:'sensor.bagno_padronale_temperatura',humidity:'sensor.bagno_padronale_umidita',lights:'light.bagno_padronale',cover:'cover.bagno_padronale'}},
  {id:'first-bathroom',modelKey:'first__Bathroom-109096',floor:'first',name:'Bagno',icon:'fa-bath',type:'indoor',entities:{temperature:'sensor.bagno_temperatura',humidity:'sensor.bagno_umidita',lights:'light.bagno',cover:'cover.bagno'}},
  {id:'first-corridor',modelKey:'first__Corridor-117360',floor:'first',name:'Corridoio',icon:'fa-arrows-left-right',type:'indoor',entities:{temperature:'sensor.corridoio_temperatura',humidity:'sensor.corridoio_umidita',lights:'light.corridoio'}},
  {id:'first-other-room',modelKey:'first__OtherRoom-109066',floor:'first',name:'Camera bambino',icon:'fa-child',type:'indoor',entities:{temperature:'sensor.camera_bambino_temperatura',humidity:'sensor.camera_bambino_umidita',lights:'light.camera_bambino',cover:'cover.camera_bambino'}},
  {id:'first-terrace-main',modelKey:'first__Terrace-101880',floor:'first',name:'Terrazza principale',icon:'fa-umbrella-beach',type:'outdoor',entities:{temperature:'sensor.terrazza_principale_temperatura',lights:'light.terrazza_principale',cover:'cover.terrazza_principale'}},
  {id:'first-terrace-secondary',modelKey:'first__Terrace-119118',floor:'first',name:'Terrazza secondaria',icon:'fa-umbrella-beach',type:'outdoor',entities:{temperature:'sensor.terrazza_secondaria_temperatura',lights:'light.terrazza_secondaria'}},
  {id:'second-living',modelKey:'second__LivingRoom-39392',floor:'second',name:'Soggiorno mansarda',icon:'fa-couch',type:'indoor',entities:{temperature:'sensor.soggiorno_mansarda_temperatura',humidity:'sensor.soggiorno_mansarda_umidita',lights:'light.soggiorno_mansarda',cover:'cover.soggiorno_mansarda'}},
  {id:'second-bedroom',modelKey:'second__Bedroom-35912',floor:'second',name:'Camera mansarda',icon:'fa-bed',type:'indoor',entities:{temperature:'sensor.camera_mansarda_temperatura',humidity:'sensor.camera_mansarda_umidita',lights:'light.camera_mansarda',cover:'cover.camera_mansarda'}},
  {id:'second-bathroom',modelKey:'second__Bathroom-37895',floor:'second',name:'Bagno mansarda',icon:'fa-bath',type:'indoor',entities:{temperature:'sensor.bagno_mansarda_temperatura',humidity:'sensor.bagno_mansarda_umidita',lights:'light.bagno_mansarda',cover:'cover.bagno_mansarda'}},
  {id:'second-equipment',modelKey:'second__EquipmentRoom-36717',floor:'second',name:'Locale tecnico',icon:'fa-screwdriver-wrench',type:'indoor',entities:{temperature:'sensor.locale_tecnico_temperatura',humidity:'sensor.locale_tecnico_umidita',lights:'light.locale_tecnico'}},
  {id:'second-terrace-main',modelKey:'second__Terrace-40381',floor:'second',name:'Terrazza mansarda',icon:'fa-umbrella-beach',type:'outdoor',entities:{temperature:'sensor.terrazza_mansarda_temperatura',lights:'light.terrazza_mansarda',cover:'cover.terrazza_mansarda'}},
  {id:'second-terrace-secondary',modelKey:'second__Terrace-42789',floor:'second',name:'Terrazza mansarda 2',icon:'fa-umbrella-beach',type:'outdoor',entities:{temperature:'sensor.terrazza_mansarda_2_temperatura',lights:'light.terrazza_mansarda_2'}}
];
